name: plotastrodata
channels:
  - anaconda
  - conda-forge
  - plotly
dependencies:
  - python>=3.10
  - astropy>=7.0
  - corner
  - dynesty
  - emcee
  - matplotlib
  - multiprocess
  - numpy>=2.0
  - pillow
  - plotly
  - ptemcee
  - scikit-image
  - scipy
  - tqdm
